### ISSUE TITLE
How to check a dev-only package?

### ISSUE THREAD

**Issue by derwaldgeist** [Meteor-Community-Packages/check-npm-versions#16]
I am using Sass for styling, so I need to reference Sass-related packages that are required during development and build only. How do I check for these kind of packages? I don't want to include any code in of these packages. Would it suffice to check on the server without any import or require()?

**Comment by copleykj** [comment]
I know this reply is a couple of years late, but better late than never I guess. Did you ever get this sorted out?

Personally I think the easiest way to accomplish this is going to be to wrap the checks in a `Meteor.isDevelopment` check.

Closing for now due to age, but feel free to discuss and reopen if necessary.
