### ISSUE TITLE
npm link

### ISSUE THREAD

**Issue by owenhoskins** [Meteor-Community-Packages/check-npm-versions#3]
Hello. I am trying to depend a local npm package "react-grid-layout" with checkNpmVersions.

By using npm link the package is symlinked in my app's node_modules folder.

checkNpmVersions doesn't throw any errors to the server or console but I get an error from React about having multiple copies loaded.

When testing without the symlink and directly npm installing the package everything works as expected and it seems checkNpmVersion is doing it's job perfectly.

Perhaps there a subtle difference between npm link and npm install that would sabotage checkNpmVersion's dependency management? 

Any clues would be greatly appreciated.

Thanks!
Owen

**Comment by copleykj** [comment]
This package isn't meant to stop the loading of 2 copies of a package when manually installing 2 copies in a project, it is meant as a way to tell app creators that they need to install an NPM package so that meteor package authors don't use `Npm.depends` within their package code. Having 2 packages that do this for the same package will cause multiple copies of the same NPM module to be loaded, which is undesirable.
