### ISSUE TITLE
How to "do the check in a separate file"?

### ISSUE THREAD

**Issue by lorensr** [Meteor-Community-Packages/check-npm-versions#7]
Readme:

> Note that you must use require rather than import, unless you do the check in a separate file

This doesn't work:

``` js
// package.js
api.mainModule('main.js');

// main.js
import '/check-npm.js';
import _ from 'lodash';

// check-npm.js
import { checkNpmVersions } from 'meteor/tmeasday:check-npm-versions';

checkNpmVersions({
  'apollo-client': '^0.3.8'
}, 'my:awesome-package');
```

**Comment by lorensr** [comment]
@tmeasday fyi – there are some open issues on this repo. noticed you weren't Watching

**Comment by tmeasday** [comment]
Hmm, I'm not sure what the issue you are seeing with the above is @lorensr? Can you make a repro app?

**Comment by lorensr** [comment]
Np, initially just gave the short version in case it was an obvious thing.
```
git clone git@github.com:apollostack/meteor-integration.git
git checkout repro
npm i
npm test
```
Well actually, fixed original error, getting a different one now:
![image](https://cloud.githubusercontent.com/assets/251288/15461764/a6c1ffea-208b-11e6-8492-d77ac878539b.png)
Should it work during a package test?

**Comment by lorensr** [comment]
I was thinking maybe the solution was to add `Npm.depends` to `package.js` and remember to comment it out when publishing, but I get the same error message as above

```js
Npm.depends({
  'apollo-client': '0.3.9',
  'express': '4.13.4',
  'graphql-tools': '0.4.1',
  'http-proxy-middleware': '0.15.0'
});
```

**Comment by tmeasday** [comment]
> Should it work during a package test?

It complains during package tests, yeah. Not sure why.

**Comment by lorensr** [comment]
It exits with code 8. Could it just do nothing if it's running during a package test? Is there a `Meteor.*` var for that?

**Comment by tmeasday** [comment]
Yeah, there is. I'm waiting to speak to @benjamn and figure out why it's failing in package tests.

**Comment by Anima-t3d** [comment]
The issue still persists. @tmeasday could it have to do with the fact that the main app did not run? As in, `meteor test-packages` does not fully use the dependencies, as far as **check-npm-versions** is concerned it is not there?

**Comment by jakelacey2012** [comment]
@tmeasday did you have a talk with @benjamn regarding this issue?

I've been having this issue running packages tests, so there is a couple of things I've found.

Here is what I'm checking for
```javascript

checkNpmVersions({
  'react-input-autosize': '1.1.x',
  'react-portal': '3.x.x',
}, 'lib-react');

```

In development it works fine, 
 - It throws an warning when the packages aren't there and doesn't when they are.

In Testing it doesn't 
 - It throws a warning both, this is because 
```javascript
require(`${name}/package.json`).version cannot find the package.
```

However if I include 
```javascript
require('react-input-autosize/package.json').version;
require('react-portal/package.json').version;
```

Below where I'm calling `checkNpmVersion`, everything works fine. *weird*

The biggest weirdness I found was that this
```javascript
require(`${name}`/package.json).version
```
works in development but  throws a cannot find module error when testing.

Hopefully that make sense, let me know if you need anymore info... If I find a way I will let this thread know..

Thanks

**Comment by tmeasday** [comment]
Hi @jakelacey2012, TBH I really don't remember where we got to with this one. Ultimately it's all about what the build system decides to bundle in the built app (which is why putting extra requires in can change things).

You can run `meteor test-packages --test-app-dir=/x/y` and have a look at the app it uses for testing if that helps.

**Comment by copleykj** [comment]
To fix this, create a directory with a `package.json` file in it that contains the necessary dependencies, and then use the `--test-app-path ./path/to/test-app` flag to point to that dir
